"""Updated game model

Revision ID: 5fc8040ef224
Revises: 25bb04f19669
Create Date: 2024-11-16 20:28:30.141961

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5fc8040ef224"
down_revision: Union[str, None] = "25bb04f19669"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "word_state")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column(
            "word_state", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
