"""Fixed PlayerModel

Revision ID: 6ac02577fe7e
Revises: f7ed1d95d836
Create Date: 2024-11-17 20:37:53.092051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac02577fe7e'
down_revision: Union[str, None] = 'f7ed1d95d836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('players_username_key', 'players', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('players_username_key', 'players', ['username'])
    # ### end Alembic commands ###
