"""Removed game_state from PlayerModel

Revision ID: c794cda72606
Revises: 6ac02577fe7e
Create Date: 2024-11-18 17:33:36.820752

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c794cda72606"
down_revision: Union[str, None] = "6ac02577fe7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "game_state")
    op.drop_constraint("players_user_id_fkey", "players", type_="foreignkey")
    op.create_foreign_key(
        None, "players", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("players", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "players",
        sa.Column(
            "username", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "players", type_="foreignkey")
    op.create_foreign_key(
        "players_user_id_fkey", "players", "users", ["user_id"], ["id"]
    )
    op.add_column(
        "games",
        sa.Column(
            "game_state", sa.BIGINT(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
